version: "3"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
  # app:
  #   container_name: "app"
  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile
  #   volumes:
  #     # - ~/.air:/src/go
  #     - ./:/src/go
  #     - $GOPATH/pkg/mod:/go/pkg/mod
  #   ports:
  #     - 8080:8080
  #   working_dir: /src/go
  #   command: ./air -c air.conf
